spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myrealm
          jwk-set-uri: http://localhost:8080/realms/myrealm/protocol/openid-connect/certs

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

keycloak:
  auth-server-url: http://localhost:8080
  realm: myrealm
  resource: auth-service
  credentials:
    secret: Xec0nXTeDHngkY7e2siYISVwRUqLwcDY
  public-client: false
  bearer-only: true
  admin:
    url: ${KEYCLOAK_ADMIN_URL:http://localhost:8080}
    realm: ${KEYCLOAK_ADMIN_REALM:myrealm}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

cors:
  allowed-origins: http://localhost:3000,http://localhost:4200

logging:
  level:
    br.com.leonardosr.auth: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configurações do OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 